name: Sincronizar GLPI - GEMS

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  sincronizar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar sincronização
        env:
          GLPI_URL_BASE: ${{ secrets.GLPI_URL_BASE }}
          GLPI_USER_TOKEN: ${{ secrets.GLPI_USER_TOKEN }}
          GLPI_APP_TOKEN: ${{ secrets.GLPI_APP_TOKEN }}
          GLPI_GRUPO_GEMS: ${{ secrets.GLPI_GRUPO_GEMS }}

          GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
          GOOGLE_SHEETS_ABA: ${{ secrets.GOOGLE_SHEETS_ABA }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}

        run: node index.js
